apiVersion: apps/v1
kind: Deployment
metadata:
  name: chessgame-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chessgame
  template:
    metadata:
      labels:
        app: chessgame
    spec:
      containers:
        - name: chessgame
          image: prasant21/chess_game